### ISSUE TITLE
Extension stopped converting: 'currency' is not defined in the unit registry

### ISSUE THREAD

**Issue by krillin666** [tchar/ulauncher-albert-calculate-anything#42]
Hey,

The extension stopped working a few days ago. I've tried multiple conversions but I get no result with any of them.

In the console I have this error: `pint.errors.UndefinedUnitError: 'currency' is not defined in the unit registry`

Thank you!

**Comment by GEkuL** [comment]
Hi there!
Have the same issue appeared after I installed the extension few days ago.
@krillin666 have you found any solution?

**Comment by fabiompneves** [comment]
Same problem here. Not only corrency but others units to. Like celsius to fahrenheit and others.

**Comment by maxime-rey** [comment]
Same here. If it helps, it happens using "internal" for me, not fixer.io.
Here's the python traceback:
```12:26:20 [crit:python] [calculate_anything.query.handlers.multi_handler._handle:60]: Exception in handler: UnitsQueryHandler: 'currency' is not defined in the unit registry
Traceback (most recent call last):
  File "/home/max/.local/share/albert/org.albert.extension.python/modules/calculate-anything/calculate_anything/query/handlers/multi_handler.py", line 55, in _handle
    result = handler.handle(query)
  File "/home/max/.local/share/albert/org.albert.extension.python/modules/calculate-anything/calculate_anything/query/handlers/base.py", line 23, in _wrapper
    return func(self, query, *args, **kwargs)
  File "/home/max/.local/share/albert/org.albert.extension.python/modules/calculate-anything/calculate_anything/query/handlers/base.py", line 57, in handle
    return self.handle_raw(query, *args, **kwargs)
  File "/home/max/.local/share/albert/org.albert.extension.python/modules/calculate-anything/calculate_anything/query/handlers/units.py", line 240, in handle_raw
    with ureg.context('currency'):
  File "/usr/lib/python3.10/contextlib.py", line 135, in __enter__
    return next(self.gen)
  File "/home/max/.local/lib/python3.10/site-packages/pint/facets/context/registry.py", line 301, in context
    self.enable_contexts(*names, **kwargs)
  File "/home/max/.local/lib/python3.10/site-packages/pint/facets/context/registry.py", line 242, in enable_contexts
    self._switch_context_cache_and_units()
  File "/home/max/.local/lib/python3.10/site-packages/pint/facets/context/registry.py", line 151, in _switch_context_cache_and_units
    self._redefine(definition)
  File "/home/max/.local/lib/python3.10/site-packages/pint/facets/context/registry.py", line 175, in _redefine
    dims_old = self._get_dimensionality(basedef.reference)
  File "/home/max/.local/lib/python3.10/site-packages/pint/facets/plain/registry.py", line 660, in _get_dimensionality
    self._get_dimensionality_recurse(input_units, 1, accumulator)
  File "/home/max/.local/lib/python3.10/site-packages/pint/facets/plain/registry.py", line 681, in _get_dimensionality_recurse
    reg = self._units[self.get_name(key)]
  File "/home/max/.local/lib/python3.10/site-packages/pint/facets/plain/registry.py", line 588, in get_name
    raise UndefinedUnitError(name_or_alias)
pint.errors.UndefinedUnitError: 'currency' is not defined in the unit registry
```

**Comment by zorzysty** [comment]
Same here 😢

**Comment by didaktiik** [comment]
I have got the same problem, unfortunately.

**Comment by GEkuL** [comment]
@maxime-rey so do you mean it works fine with the flex.io only?

**Comment by fabiompneves** [comment]
It doesn't work with internal or fixer.io. But not only currency is buggy the measures and other conversions doesn't work to

**Comment by stingray21** [comment]
Is there any update on this? I really miss using this extension

**Comment by tchar** [comment]
Can you let me know if #48 fixed this?

**Comment by sebastian-65** [comment]
@tchar Conversion works now. Thank you so much for fixing this!
